apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: clone-repo
        image: alpine/git
        command:
        - sh
        - -c
        - |
          echo "Setting up SSH key..."
          mkdir -p /root/.ssh
          cp /tmp-ssh/id_rsa /root/.ssh/id_rsa || echo "Copy failed"
          chmod 600 /root/.ssh/id_rsa || echo "Chmod failed"
          {{- if and .Values.gitCredentials.username .Values.gitCredentials.token }}
          git clone --branch {{ .Values.nginx.gitBranch }} https://{{ .Values.gitCredentials.username }}:{{ .Values.gitCredentials.token }}@{{ trimPrefix "https://" .Values.nginx.gitRepo }} /git-data
          {{- else }}
          git clone --branch {{ .Values.nginx.gitBranch }} {{ .Values.nginx.gitRepo }} /git-data
          {{- end }}
          mv /git-data/* /usr/share/nginx/html/
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        {{- if .Values.gitCredentials.ssh }}
        - name: ssh-key
          mountPath: /tmp-ssh
        env:
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        - name: ssh-key
          secret:
            secretName: {{ .Values.nginx.gitCredentials.secretName }}
            items:
            - key: {{ .Values.nginx.gitCredentials.sshKey }}
              path: id_rsa
        {{- end }}
        {{- if and .Values.gitCredentials.username .Values.gitCredentials.token }}
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.nginx.gitCredentials.secretName }}
              key: {{ .Values.nginx.gitCredentials.usernameKey }}
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.nginx.gitCredentials.secretName }}
              key: {{ .Values.nginx.gitCredentials.tokenKey }}
        {{- end }}
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
          - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
      {{- if .Values.gitCredentials.ssh }}
      - name: ssh-key
        secret:
          secretName: {{ .Values.nginx.gitCredentials.secretName }}
          items:
          - key: {{ .Values.nginx.gitCredentials.sshKey }}
            path: id_rsa
      {{- end }}