apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: clone-repo
        image: alpine/git
        command:
        - sh
        - -c
        - |
          git clone --branch {{ .Values.nginx.gitBranch }} {{ .Values.nginx.gitRepo }} /git-data
          mv /git-data/* /usr/share/nginx/html/
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
          - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
