apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-credentials
type: Opaque
data:
  username: {{ .Values.gitCredentials.username | b64enc }}
  token: {{ .Values.gitCredentials.token | b64enc }}