apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-operator-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: simple-git-rollout-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: git-operator-role
  apiGroup: rbac.authorization.k8s.io

