apiVersion: v1
kind: Secret
metadata:
  name: simple-git-rollout-operator-git-credentials
type: Opaque
data:
  username: {{ .Values.gitCredentials.username | b64enc }}
  token: {{ .Values.gitCredentials.token | b64enc }}
  ssh: {{ .Values.gitCredentials.ssh | b64enc }}