apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-operator-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: simple-git-rollout-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: git-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

