name: "datadirsync"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: "Checking out"
      uses: actions/checkout@v1

    - name: "Determine Tag or Latest"
      id: tag_or_latest
      run: |
        TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "latest")
        echo "Chosen TAG: $TAG"
        echo ::set-output name=TAG::$TAG

    - name: Debug version
      run: echo "VERSION=${{ steps.tag_or_latest.outputs.TAG }}"

    - name: "Building docker image"
      if: github.repository == 'georchestra/datadirsync-k8s-agent' && github.actor != 'dependabot[bot]'
      run: docker build -t georchestra/datadirsync-k8s-agent:${{ steps.tag_or_latest.outputs.TAG }} ./agent

    - name: "Logging in docker.io"
      if: github.repository == 'georchestra/datadirsync-k8s-agent' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

    - name: "Push image to docker.io with tag"
      if: github.repository == 'georchestra/datadirsync-k8s-agent' && github.actor != 'dependabot[bot]' && github.event_name == 'pull_request'
      run: |
        docker push georchestra/datadirsync-k8s-agent:${{ steps.tag_or_latest.outputs.TAG }}

    - name: "Push image to docker.io tagged as latest"
      if: github.repository == 'georchestra/datadirsync-k8s-agent' && github.actor != 'dependabot[bot]' && github.event_name == 'pull_request'
      run: |
        docker tag georchestra/datadirsync-k8s-agent:${{ steps.tag_or_latest.outputs.TAG }} georchestra/datadirsync-k8s-agent:latest
        docker push georchestra/datadirsync-k8s-agent:latest

    - name: "Update Docker Hub Description"
      if: github.ref == 'refs/heads/main' && github.repository == 'georchestra/datadirsync-k8s-agent' && github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: georchestra/datadirsync-k8s-agent
        readme-filepath: ./DOCKER_HUB.md
        short-description: 'DatadirSync K8s Agent for geOrchestra SDI'

